import 'dart:io';

/// Generator for clean feature-first architecture Flutter project structure.
class ScaffoldGenerator {
  final String projectName;
  final String targetPath;
  final bool includeRiverpod;
  final bool includeGoRouter;

  ScaffoldGenerator({
    required this.projectName,
    required this.targetPath,
    this.includeRiverpod = true,
    this.includeGoRouter = true,
  });

  /// Generates the directory hierarchy and template files.
  Future<int> generate() async {
    final Directory baseDir = Directory('$targetPath/$projectName');
    if (!await baseDir.exists()) {
      await baseDir.create(recursive: true);
    }

    final List<String> directories = [
      'lib/core/constants',
      'lib/core/network',
      'lib/core/router',
      'lib/core/theme',
      'lib/core/utils',
      'lib/features/home/data/models',
      'lib/features/home/data/repositories',
      'lib/features/home/domain/repositories',
      'lib/features/home/domain/usecases',
      'lib/features/home/presentation/controllers',
      'lib/features/home/presentation/views',
      'lib/features/home/presentation/widgets',
      'test/features/home',
      '.github/workflows',
    ];

    int createdFilesCount = 0;

    for (final dirPath in directories) {
      final Directory dir = Directory('${baseDir.path}/$dirPath');
      await dir.create(recursive: true);
    }

    // Write main.dart
    await _writeFile('${baseDir.path}/lib/main.dart', _buildMainTemplate());
    createdFilesCount++;

    // Write router
    await _writeFile(
      '${baseDir.path}/lib/core/router/app_router.dart',
      _buildRouterTemplate(),
    );
    createdFilesCount++;

    // Write GitHub CI workflow
    await _writeFile(
      '${baseDir.path}/.github/workflows/ci.yml',
      _buildCiWorkflowTemplate(),
    );
    createdFilesCount++;

    // Write pubspec.yaml template
    await _writeFile(
      '${baseDir.path}/pubspec.yaml',
      _buildPubspecTemplate(),
    );
    createdFilesCount++;

    return createdFilesCount;
  }

  Future<void> _writeFile(String filePath, String content) async {
    final File file = File(filePath);
    await file.writeAsString(content);
  }

  String _buildMainTemplate() {
    return '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'core/router/app_router.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: '$projectName',
      theme: ThemeData.dark(useMaterial3: true),
      routerConfig: appRouter,
    );
  }
}
''';
  }

  String _buildRouterTemplate() {
    return '''
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final GoRouter appRouter = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const Scaffold(
        body: Center(child: Text('Welcome to $projectName')),
      ),
    ),
  ],
);
''';
  }

  String _buildCiWorkflowTemplate() {
    return '''
name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart analyze
      - run: flutter test
''';
  }

  String _buildPubspecTemplate() {
    return '''
name: $projectName
description: A new clean architecture Flutter project generated by flutter_clean_cli.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  go_router: ^13.0.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
''';
  }
}
